spring:
  application:
    name: bankAppOk

  jpa:
    hibernate:
      ddl-auto: create

  data:
    mongodb:
      uri: mongodb+srv://1:1@cluster0.vlexj.mongodb.net/test
      database: BankDocuments

