spring:
  application:
    name: bankAppOk

  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: validate

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/bankDb
    username: postgres
    password: 1

  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: bankDocuments
  mvc:
    hiddenmethod:
      filter:
        enabled: true


#  thymeleaf:
#    prefix: classpath:/templates
#    suffix: .html