spring:
  application:
    name: bankAppOk


  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: none

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/bankDb
    username: postgres
    password: 1

  data:
    mongodb:
      uri: mongodb+srv://1:1@cluster0.vlexj.mongodb.net/test
      database: BankDocuments